spring:
  application:
    name: restaurant-service
  datasource:
    url: jdbc:postgresql://localhost:5432/restaurant_service_db
    username: postgres
    password: vkdj@2000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8083